var countryAgg={207	:["	World	","	Americas	","	South America	"],
119	:["	World	","	Europe	","	Northern Europe	"],
160	:["	World	","	Oceania	","	Polynesia	"],
189	:["	World	","	Americas	","	Caribbean	"],
231	:["	World	","	Americas	","	Northern America	"],
220	:["	World	","	Americas	","	Caribbean	"],
85	:["	World	","	Americas	","	Northern America	"],
110	:["	World	","	Asia	","	Eastern Asia	"],
104	:["	World	","	Europe	","	Northern Europe	"],
127	:["	World	","	Oceania	","	Micronesia	"],
176	:["	World	","	Asia	","	South-Eastern Asia	"],
58	:["	World	","	Americas	","	South America	"],
8	:["	World	","	Americas	","	Caribbean	"],
23	:["	World	","	Americas	","	Central America	"],
156	:["	World	","	Oceania	","	Australia & New Zealand	"],
206	:["	World	","	Africa	","	Northern Africa	"],
240	:["	World	","	Americas	","	Caribbean	"],
89	:["	World	","	Americas	","	Central America	"],
280	:["	World	","	Americas	","	Caribbean	"],
174	:["	World	","	Europe	","	Southern Europe	"],
80	:["	World	","	Europe	","	Southern Europe	"],
64	:["	World	","	Europe	","	Northern Europe	"],
217	:["	World	","	Africa	","	Western Africa	"],
177	:["	World	","	Americas	","	Caribbean	"],
105	:["	World	","	Asia	","	Western Asia	"],
66	:["	World	","	Oceania	","	Melanesia	"],
143	:["	World	","	Africa	","	Northern Africa	"],
223	:["	World	","	Asia	","	Western Asia	"],
186	:["	World	","	Europe	","	Southern Europe	"],
129	:["	World	","	Africa	","	Eastern Africa	"],
193	:["	World	","	Africa	","	Middle Africa	"],
15	:["	World	","	Europe	","	Western Europe	"],
10	:["	World	","	Oceania	","	Australia & New Zealand	"],
259	:["	World	","	Europe	","	Northern Europe	"],
215	:["	World	","	Africa	","	Eastern Africa	"],
154	:["	World	","	Europe	","	Southern Europe	"],
67	:["	World	","	Europe	","	Northern Europe	"],
116	:["	World	","	Asia	","	Eastern Asia	"],
44	:["	World	","	Americas	","	South America	"],
236	:["	World	","	Americas	","	South America	"],
170	:["	World	","	Americas	","	South America	"],
183	:["	World	","	Europe	","	Eastern Europe	"],
101	:["	World	","	Asia	","	South-Eastern Asia	"],
61	:["	World	","	Africa	","	Middle Africa	"],
14	:["	World	","	Americas	","	Caribbean	"],
57	:["	World	","	Europe	","	Eastern Europe	"],
226	:["	World	","	Africa	","	Eastern Africa	"],
21	:["	World	","	Americas	","	South America	"],
166	:["	World	","	Americas	","	Central America	"],
100	:["	World	","	Asia	","	Southern Asia	"],
149	:["	World	","	Asia	","	Southern Asia	"],
5	:["	World	","	Oceania	","	Polynesia	"],
203	:["	World	","	Europe	","	Southern Europe	"],
150	:["	World	","	Europe	","	Western Europe	"],
235	:["	World	","	Asia	","	Central Asia	"],
146	:["	World	","	Europe	","	Eastern Europe	"],
210	:["	World	","	Europe	","	Northern Europe	"],
60	:["	World	","	Americas	","	Central America	"],
285	:["	World	","	Europe	","	Northern Europe	"],
134	:["	World	","	Europe	","	Southern Europe	"],
351	:["	World	","	Asia	","	Eastern Asia	"],
147	:["	World	","	Africa	","	Southern Africa	"],
95	:["	World	","	Americas	","	Central America	"],
96	:["	World	","	Asia	","	Eastern Asia	"],
194	:["	World	","	Asia	","	Western Asia	"],
7	:["	World	","	Africa	","	Middle Africa	"],
243	:["	World	","	Oceania	","	Polynesia	"],
250	:["	World	","	Africa	","	Middle Africa	"],
94	:["	World	","	Europe	","	Southern Europe	"],
216	:["	World	","	Asia	","	South-Eastern Asia	"],
29	:["	World	","	Africa	","	Eastern Africa	"],
106	:["	World	","	Europe	","	Southern Europe	"],
144	:["	World	","	Africa	","	Eastern Africa	"],
157	:["	World	","	Americas	","	Central America	"],
132	:["	World	","	Asia	","	Southern Asia	"],
155	:["	World	","	Oceania	","	Melanesia	"],
202	:["	World	","	Africa	","	Southern Africa	"],
52	:["	World	","	Asia	","	Western Asia	"],
3	:["	World	","	Europe	","	Southern Europe	"],
214	:["	World	","	Asia	","	Eastern Asia	"],
39	:["	World	","	Africa	","	Middle Africa	"],
122	:["	World	","	Africa	","	Southern Africa	"],
145	:["	World	","	Oceania	","	Micronesia	"],
167	:["	World	","	Europe	","	Eastern Europe	"],
151	:["	World	","	Americas	","	Caribbean	"],
88	:["	World	","	Oceania	","	Micronesia	"],
125	:["	World	","	Europe	","	Western Europe	"],
142	:["	World	","	Americas	","	Caribbean	"],
162	:["	World	","	Europe	","	Northern Europe	"],
270	:["	World	","	Africa	","	Eastern Africa	"],
190	:["	World	","	Americas	","	Northern America	"],
123	:["	World	","	Africa	","	Western Africa	"],
99	:["	World	","	Europe	","	Northern Europe	"],
272	:["	World	","	Europe	","	Southern Europe	"],
33	:["	World	","	Americas	","	Northern America	"],
184	:["	World	","	Africa	","	Eastern Africa	"],
36	:["	World	","	Americas	","	Caribbean	"],
218	:["	World	","	Oceania	","	Polynesia	"],
117	:["	World	","	Asia	","	Eastern Asia	"],
6	:["	World	","	Europe	","	Southern Europe	"],
171	:["	World	","	Asia	","	South-Eastern Asia	"],
198	:["	World	","	Europe	","	Southern Europe	"],
56	:["	World	","	Americas	","	Caribbean	"],
197	:["	World	","	Africa	","	Western Africa	"],
69	:["	World	","	Americas	","	South America	"],
191	:["	World	","	Americas	","	Caribbean	"],
112	:["	World	","	Asia	","	Western Asia	"],
113	:["	World	","	Asia	","	Central Asia	"],
212	:["	World	","	Asia	","	Western Asia	"],
48	:["	World	","	Americas	","	Central America	"],
22	:["	World	","	Americas	","	Caribbean	"],
40	:["	World	","	Americas	","	South America	"],
18	:["	World	","	Asia	","	Southern Asia	"],
230	:["	World	","	Europe	","	Eastern Europe	"],
357	:["	World	","	Asia	","	Eastern Asia	"],
9	:["	World	","	Americas	","	South America	"],
238	:["	World	","	Africa	","	Eastern Africa	"],
128	:["	World	","	Asia	","	Eastern Asia	"],
213	:["	World	","	Asia	","	Central Asia	"],
274	:["	World	","	Europe	","	Northern Europe	"],
181	:["	World	","	Africa	","	Eastern Africa	"],
79	:["	World	","	Europe	","	Western Europe	"],
188	:["	World	","	Americas	","	Caribbean	"],
72	:["	World	","	Africa	","	Eastern Africa	"],
201	:["	World	","	Africa	","	Eastern Africa	"],
172	:["	World	","	Oceania	","	Polynesia	"],
249	:["	World	","	Asia	","	Western Asia	"],
103	:["	World	","	Asia	","	Western Asia	"],
192	:["	World	","	Europe	","	Southern Europe	"],
256	:["	World	","	Europe	","	Western Europe	"],
98	:["	World	","	Europe	","	Southern Europe	"],
148	:["	World	","	Oceania	","	Micronesia	"],
38	:["	World	","	Asia	","	Southern Asia	"],
178	:["	World	","	Africa	","	Eastern Africa	"],
169	:["	World	","	Americas	","	South America	"],
276	:["	World	","	Africa	","	Northern Africa	"],
239	:["	World	","	Americas	","	Caribbean	"],
54	:["	World	","	Europe	","	Northern Europe	"],
234	:["	World	","	Americas	","	South America	"],
185	:["	World	","	Europe	","	Eastern Europe	"],
74	:["	World	","	Africa	","	Middle Africa	"],
35	:["	World	","	Africa	","	Western Africa	"],
131	:["	World	","	Asia	","	South-Eastern Asia	"],
228	:["	World	","	Europe	","	Eastern Europe	"],
118	:["	World	","	Asia	","	Western Asia	"],
180	:["	World	","	Oceania	","	Micronesia	"],
244	:["	World	","	Oceania	","	Polynesia	"],
260	:["	World	","	Europe	","	Northern Europe	"],
120	:["	World	","	Asia	","	South-Eastern Asia	"],
283	:["	World	","	Europe	","	Northern Europe	"],
75	:["	World	","	Africa	","	Western Africa	"],
27	:["	World	","	Europe	","	Eastern Europe	"],
84	:["	World	","	Europe	","	Southern Europe	"],
237	:["	World	","	Asia	","	South-Eastern Asia	"],
121	:["	World	","	Asia	","	Western Asia	"],
83	:["	World	","	Oceania	","	Micronesia	"],
140	:["	World	","	Europe	","	Western Europe	"],
158	:["	World	","	Africa	","	Western Africa	"],
108	:["	World	","	Asia	","	Central Asia	"],
124	:["	World	","	Africa	","	Northern Africa	"],
87	:["	World	","	Americas	","	Caribbean	"],
126	:["	World	","	Europe	","	Northern Europe	"],
211	:["	World	","	Europe	","	Western Europe	"],
11	:["	World	","	Europe	","	Western Europe	"],
196	:["	World	","	Africa	","	Eastern Africa	"],
273	:["	World	","	Europe	","	Southern Europe	"],
199	:["	World	","	Europe	","	Eastern Europe	"],
63	:["	World	","	Europe	","	Northern Europe	"],
279	:["	World	","	Americas	","	Caribbean	"],
70	:["	World	","	Oceania	","	Polynesia	"],
153	:["	World	","	Oceania	","	Melanesia	"],
1	:["	World	","	Asia	","	Western Asia	"],
163	:["	World	","	Oceania	","	Micronesia	"],
227	:["	World	","	Oceania	","	Polynesia	"],
37	:["	World	","	Africa	","	Middle Africa	"],
130	:["	World	","	Africa	","	Eastern Africa	"],
229	:["	World	","	Europe	","	Northern Europe	"],
208	:["	World	","	Asia	","	Central Asia	"],
173	:["	World	","	Europe	","	Eastern Europe	"],
28	:["	World	","	Asia	","	South-Eastern Asia	"],
91	:["	World	","	Americas	","	South America	"],
4	:["	World	","	Africa	","	Northern Africa	"],
68	:["	World	","	Europe	","	Western Europe	"],
81	:["	World	","	Africa	","	Western Africa	"],
175	:["	World	","	Africa	","	Western Africa	"],
200	:["	World	","	Asia	","	South-Eastern Asia	"],
195	:["	World	","	Africa	","	Western Africa	"],
93	:["	World	","	Americas	","	Caribbean	"],
221	:["	World	","	Asia	","	Western Asia	"],
47	:["	World	","	Oceania	","	Polynesia	"],
182	:["	World	","	Africa	","	Eastern Africa	"],
19	:["	World	","	Americas	","	South America	"],
284	:["	World	","	Europe	","	Northern Europe	"],
97	:["	World	","	Europe	","	Eastern Europe	"],
258	:["	World	","	Americas	","	Caribbean	"],
51	:["	World	","	Europe	","	Eastern Europe	"],
138	:["	World	","	Americas	","	Central America	"],
224	:["	World	","	Americas	","	Caribbean	"],
114	:["	World	","	Africa	","	Eastern Africa	"],
135	:["	World	","	Americas	","	Caribbean	"],
16	:["	World	","	Asia	","	Southern Asia	"],
12	:["	World	","	Americas	","	Caribbean	"],
86	:["	World	","	Americas	","	Caribbean	"],
90	:["	World	","	Africa	","	Western Africa	"],
55	:["	World	","	Americas	","	Caribbean	"],
248	:["	World	","	Europe	","	Southern Europe	"],
115	:["	World	","	Asia	","	South-Eastern Asia	"],
179	:["	World	","	Asia	","	Western Asia	"],
2	:["	World	","	Asia	","	Southern Asia	"],
255	:["	World	","	Europe	","	Western Europe	"],
102	:["	World	","	Asia	","	Southern Asia	"],
26	:["	World	","	Asia	","	South-Eastern Asia	"],
264	:["	World	","	Europe	","	Northern Europe	"],
165	:["	World	","	Asia	","	Southern Asia	"],
251	:["	World	","	Africa	","	Eastern Africa	"],
107	:["	World	","	Africa	","	Western Africa	"],
137	:["	World	","	Africa	","	Eastern Africa	"],
141	:["	World	","	Asia	","	Eastern Asia	"],
32	:["	World	","	Africa	","	Middle Africa	"],
222	:["	World	","	Africa	","	Northern Africa	"],
17	:["	World	","	Americas	","	Northern America	"],
168	:["	World	","	Oceania	","	Melanesia	"],
65	:["	World	","	Americas	","	South America	"],
205	:["	World	","	Africa	","	Northern Africa	"],
49	:["	World	","	Americas	","	Caribbean	"],
53	:["	World	","	Africa	","	Western Africa	"],
62	:["	World	","	Africa	","	Eastern Africa	"],
20	:["	World	","	Africa	","	Southern Africa	"],
133	:["	World	","	Africa	","	Western Africa	"],
50	:["	World	","	Asia	","	Western Asia	"],
73	:["	World	","	Asia	","	Western Asia	"],
219	:["	World	","	Oceania	","	Polynesia	"],
233	:["	World	","	Africa	","	Western Africa	"],
277	:["	World	","	Africa	","	Eastern Africa	"],
46	:["	World	","	Africa	","	Middle Africa	"],
164	:["	World	","	Oceania	","	Micronesia	"],
13	:["	World	","	Asia	","	Western Asia	"],
82	:["	World	","	Europe	","	Southern Europe	"],
159	:["	World	","	Africa	","	Western Africa	"],
278	:["	World	","	Americas	","	Caribbean	"],
245	:["	World	","	Asia	","	Western Asia	"],
299	:["	World	","	Asia	","	Western Asia	"],
209	:["	World	","	Africa	","	Southern Africa	"],
109	:["	World	","	Americas	","	Caribbean	"],
76	:["	World	","	Asia	","	Western Asia	"],
45	:["	World	","	Africa	","	Eastern Africa	"],
161	:["	World	","	Oceania	","	Australia & New Zealand	"],
136	:["	World	","	Africa	","	Western Africa	"],
41	:["	World	","	Asia	","	Eastern Asia	"],
59	:["	World	","	Africa	","	Northern Africa	"],
187	:["	World	","	Africa	","	Western Africa	"],
225	:["	World	","	Asia	","	Western Asia	"],
25	:["	World	","	Oceania	","	Melanesia	"]}
